#!/usr/bin/lua
local uci = require('simple-uci').cursor()
local autil = require 'pump-autoupdater-wifi-fallback.util'
local util = require 'gluon.util'
local bit = require 'bit'
local fcntl = require 'posix.fcntl'
local unistd = require 'posix.unistd'

local configname = 'pump-autoupdater-wifi-fallback'
local lockfilename = '/var/lock/' .. configname .. '.lock'
local force = false
local min_uptime_secs = 3600
local branch_name = uci:get('autoupdater', 'settings', 'branch')

local lockfd, err = fcntl.open(lockfilename, bit.bor(fcntl.O_WRONLY, fcntl.O_CREAT), 384) -- mode 0600
if not lockfd then
  autil.log('err', err)
  local err_verbose = string.format("Unable to get file descriptor for lock file %s .", lockfilename)
  autil.log('err', err_verbose)
  os.exit(1)
end

local ok, _ = fcntl.fcntl(lockfd, fcntl.F_SETLK, {
  l_start = 0,
  l_len = 0,
  l_type = fcntl.F_WRLCK,
  l_whence = unistd.SEEK_SET,
})
if not ok then
  local err_msg = string.format("Unable to lock file %s. ", lockfilename) ..
    "Make sure there is no other instance of this script running."
  autil.log('err', err_msg)
  os.exit(1)
end

local function parse_args()
local i = 1
  while arg[i] do
    if arg[i] == '-f' then
      force = true
    elseif arg[i] == '-b' then
      i=i+1

      if not arg[i] then
        autil.log('err', 'Error parsing command line: expected branch name')
        os.exit(1)
      end

      branch_name = arg[i]
    else
      autil.log('err', "Error parsing command line: unexpected argument: '" .. arg[i] .. "'")
      os.exit(1)
    end
    i = i+1
  end
end

local function preflight_check()
  if not uci:get_bool(configname, 'settings', 'enabled') then
    return false
  end
  if not uci:get_bool('autoupdater', 'settings', 'enabled') then
    return false
  end
  if tonumber(util.readfile('/proc/uptime'):match('^([^ ]+) ')) < min_uptime_secs then
    return false
  end

  return true
end

local function connectivity_check()
  -- The fallback is only meant to recover nodes that lost mesh connectivity.
  -- Do not check IPv4 default routes or update-server reachability here; a
  -- local WAN uplink without a batman-adv gateway is irrelevant for this use
  -- case.
  --
  -- batctl gwl always prints a header containing MAC addresses such as
  -- MainIF/MAC and bat0/MAC, even when no gateway is available. Therefore we
  -- must not search for an arbitrary MAC address. Instead, match real gateway
  -- table rows only, e.g.:
  --   * 02:ca:ff:ee:01:47 (255) 02:ca:ff:ee:01:47 [ mesh-vpn]: ...
  local f = io.popen('batctl gwl 2>/dev/null')
  if f then
    for line in f:lines() do
      if line:match('^%s*%*?%s*%x%x:%x%x:%x%x:%x%x:%x%x:%x%x%s+%(%s*%d+%)%s+%x%x:%x%x:%x%x:%x%x:%x%x:%x%x%s+%[') then
        f:close()
        return true
      end
    end
    f:close()
  end

  autil.log('out', 'mesh gateway check failed')
  return false
end

local function run_autoupdater()
  autil.log('out', 'executing the autoupdater...')
  os.execute('/usr/sbin/autoupdater -f -b ' .. branch_name)
end

local function file_exists(path)
  local f = io.open(path, 'r')
  if f then
    f:close()
    return true
  end
  return false
end

local function pump_installed()
  return uci:get('pump', 'settings') ~= nil or file_exists('/etc/config/pump')
end

local function restore_pump_configuration()
  if pump_installed() and file_exists('/lib/gluon/upgrade/335-gluon-pump') then
    autil.log('out', 'restoring PUMP-generated configuration')
    os.execute('/lib/gluon/upgrade/335-gluon-pump')
  end
end

local function switch_to_fallback_mode(radio, ssid, bssid)
  autil.log('out', 'connecting to '  .. radio .. ' ' .. ssid .. ' ' .. bssid)
  uci:delete_all('wireless', 'wifi-iface')
  uci:section('wireless', 'wifi-iface', 'fallback', {
    device = radio,
    network = 'fallback',
    mode = 'sta',
    disabled = false,
    macaddr = util.generate_mac(3, 10),
    bssid = bssid,
    ssid = ssid,
    ifname = 'fallback',
    encryption = 'none',
  })
  uci:set('wireless', radio, 'disabled', false)
  uci:save('wireless')

  os.execute('wifi')
  os.execute('sleep 5')
  uci:revert('wireless')
  restore_pump_configuration()
  os.execute('sleep 20')
end

local function revert_to_standard_mode()
  autil.log('out', 'going back to standard mode')
  restore_pump_configuration()
  os.execute('/etc/init.d/network restart')
  os.execute('sleep 30')
end

parse_args()

if not uci:get('autoupdater', branch_name) then
  autil.log('err', 'Cant find configuration for branch: ' .. branch_name)
  os.exit(1)
end

if (force or preflight_check()) and not connectivity_check() then
  local offset = 2 * 3600
  local unreachable_since = os.time()
  if not uci:get('pump-autoupdater-wifi-fallback', 'settings', 'unreachable_since') then
    uci:set(configname, 'settings', 'unreachable_since', unreachable_since)
  else
    uci:set(configname, 'settings', 'last_run', unreachable_since)
    unreachable_since = uci:get(configname, 'settings', 'unreachable_since')
  end
  uci:save(configname)

  if force or tonumber(unreachable_since) + offset < os.time() then
    autil.log('out', 'going to fallback mode')
    for radio, netlist in pairs(autil.get_available_wifi_networks()) do
      for _, net in ipairs(netlist) do
        switch_to_fallback_mode(radio, net.ssid, net.bssid)
        if run_autoupdater() == 0 then
          break
        end
      end
    end
    -- this is only reached if no updated happened
    revert_to_standard_mode()
  end
else
  uci:delete(configname, 'settings', 'unreachable_since')
  uci:delete(configname, 'settings', 'last_run')
  uci:save(configname)
end