#!/bin/sh

GLUON="$(cat /lib/gluon/release)"
GLUON="$(echo ${GLUON%~*})"
EOLFILE="/lib/gluon/eol-devices-${GLUON}"

N1="$(get_image_name)"
N2="${N1%-*}"

RC1="$(grep "${N1}" "${EOLFILE}" >/dev/null ; echo $?)"
RC2="$(grep "${N2}" "${EOLFILE}" >/dev/null ; echo $?)"

if [ $RC1 -eq 0 -o $RC2 -eq 0 ]; then
  branch=$(uci get autoupdater.settings.branch)
  if [ "${branch}" != "deadend" ]; then
    uci set autoupdater.settings.branch='deadend'
    uci commit autoupdater
    HOSTNAME="$(uci get system.@system[0].hostname)"
    uci set system.@system[0].hostname="$(echo ${HOSTNAME})-EOL"
    uci commit system
  fi
fi
