#!/bin/sh

# pump_wan and pump_wan6 are registered with gluon-wan-dnsmasq through
# interface.d. Rebuild its complete resolver list whenever either address
# family changes; update.lua preserves static DNS and all other WAN uplinks.
case "$INTERFACE:$ACTION" in
	pump_wan:ifup|pump_wan:ifupdate|pump_wan:ifdown|\
	pump_wan6:ifup|pump_wan6:ifupdate|pump_wan6:ifdown)
		/lib/gluon/wan-dnsmasq/update.lua
		;;
esac

exit 0
